### PR TITLE
fix printing of tables inside arrays and https://github.com/JuliaLang/julia/issues/46454

### LINKED ISSUE #39: TOML.print produces invalid/unparsable output
I'm trying to represent what's probably a slightly more complex structure than is usually found it TOML.

```toml
[[dataset.loader]]
driver = "nested"
loaders = ["gzip", { driver = "csv", args = {delim = "\t"}}]
```

This is parsed without issue, but `TOML.print` produces invalid output.

```toml
[[dataset.loader]]
driver = "nested"
loaders = ["gzip", driver = "csv"

[args]
delim = "\t"
]
```

This seems to be the MWE to produce an error from originally valid TOML:
```julia
TOML.parse(sprint(TOML.print, TOML.parse("x = [1, { a = 2, b = 3}]")))
```

This failure to round-trip is particularly problematic for my use case, as I'm trying to have a file which is written by machine/human and automatically updated.

### LINKED ISSUE #46454: TOML: using to_toml option may produce incorrect TOML
Here is is a simplified example to illustrate the issue I'm seeing with using the TOML writer with the `to_toml` option for writing a custom type.  It seems that when using the to_toml option,  TOML print doesn't print the correct TOML.

I expect the `hello = "world"` to not be combined with the `[b]` table.

I'm using Julia 1.8 on both a M1 Mac (arm64) and an Intel Mac.

Just looking to see if anyone else is seeing this and if my understanding is correct.

```
using TOML

struct Foo
    a::Int64
    b::Float64
end

struct Bar
    c::Float64
    d::String
end


f = Foo(2,9.9)
b = Bar(1.345, "hello")

dd = Dict("hello"=>"world", "f"=>f,  "b"=>b)

toDict(foo::Foo) = Dict("a"=>foo.a, "b"=>foo.b)
toDict(bar::Bar) = Dict("c"=>bar.c, "d"=>bar.d)

TOML.print(toDict,dd)
```
which results in the "hello" being added to the `b` table in the TOML.
```
[f]
b = 9.9
a = 2

[b]
c = 1.345
d = "hello"
hello = "world"
```

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes https://github.com/JuliaLang/TOML.jl/issues/39
Fixes https://github.com/JuliaLang/julia/issues/46454

### CODE REVIEW

**Comment by tecosaur** [comment]
I've just tested this, and can confirm that in my previously-broken use case, it now works.

One minor comment, that's more style than anything else, might it be possible to use inline Dicts for short expressions? At the moment the eager expansion into non-inline dicts can make the TOML output a bit noiser than need be.

For example, unprocessed:
```toml
[["GTEx v8 transcript tpm"]]
stuff="..."
    [["GTEx v8 transcript tpm".loader]]
    stuff="..."
        [["GTEx v8 transcript tpm".loader.loaders]]
        driver = "csv"
        args = { header = 3 }
```
becomes (via a parsing round-trip)
```toml
[["GTEx v8 transcript tpm"]]
stuff="..."
    [["GTEx v8 transcript tpm".loader]]
    stuff="..."
        [["GTEx v8 transcript tpm".loader.loaders]]
        driver = "csv"
        
            ["GTEx v8 transcript tpm".loader.loaders.args]
            header = 3
```
which I think is quite simply harder to read.

Would it take much to add a heuristic along the lines of "if number of key-value pairs less than (some N) and inline dict representation is <72 characters long, use an inline dict" ?

**Comment by KristofferC** [comment]
Yeah, there are some heuristics we could probably improve here. It would be good to see what other TOML exporters do. Do they have some API where you specify how things should look or do they just go via heuristics etc? Some research here could help us decide how to best move forward.

**Comment by tecosaur** [comment]
Glad to see this merged! I'm guessing this will make its way into patch versions of Julia? Or will I need to require Julia 1.9+ in my package?

Lastly, re: style, seems like I should probably make a new issue for that.

**Comment by tecosaur** [comment]
If someone might answer my question in the comment above on which versions of Julia this fix will be found in, that would be nice :slightly_smiling_face:.

**Comment by KristofferC** [comment]
Will be in 1.9. Might be in 1.8.4.

**Comment by tecosaur** [comment]
Thanks, that's helpful to know :+1:

**Pull request merged**
