### PR TITLE
fix #13

### LINKED ISSUE #13: inconsistent empty keys parse/print
since there is no `null` type in TOML specification, people are supposed to use an empty field to represent this, but the `TOML.print` function does not implement this correctly, e.g

```julia
julia> s = """
       user = "me"
       [julia]
       [option]
       """
"user = \"me\"\n[julia]\n[option]\n"

julia> d = TOML.parse(s)
Dict{String,Any} with 3 entries:
  "julia"  => Dict{String,Any}()
  "option" => Dict{String,Any}()
  "user"   => "me"

julia> TOML.print(d) # incorrect
user = "me"
```

See also: https://github.com/toml-lang/toml/issues/30

### PR DESCRIPTION
**Pull request by Roger-luo**
actually I find it's quite easy to fix

### CODE REVIEW

**Comment by Roger-luo** [comment]
ummm.... tests fail seems not related?

**Comment by KristofferC** [comment]
> ummm.... tests fail seems not related?

Well:

```
Table: Error During Test at D:\a\TOML.jl\TOML.jl\test\readme.jl:672
 Unexpected Pass
 Expression: roundtrip(str)
 Got correct result, please change to @test if no longer broken.
```

**Comment by Roger-luo** [comment]
:-) I missed that lol, should be fixed now.

**Comment by Roger-luo** [comment]
@KristofferC bump

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/38746

**Pull request merged**
