### PR TITLE
Debugging the lcov.info file

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Okay, now we are getting somewhere.

Here is what the `lcov.info` file looks like when I run tests locally and run `CoverageTools` locally:

01-coverage-local

Here is what the `lcov.info` file looks like from GitHub Actions:

02-coverage-gha-1

**Comment by DilumAluthge** [comment]
It seems like some of the jobs are just not generating the `.jl.XXX.cov` files. That seems like it might be a bug in the `julia-runtest` action.

**Comment by KristofferC** [comment]
Even so, all jobs should execute almost the same code so it should still show things as covered?

**Comment by DilumAluthge** [comment]
> Even so, all jobs should execute almost the same code so it should still show things as covered?

Correct.

There's one (or more) suspicious things going on here.

**Comment by DilumAluthge** [comment]
The `lcov.info` files that are being generated on CI just seem.... incorrect.

**Comment by DilumAluthge** [comment]
Okay, here is a breakthrough: 

It's not just the `lcov.info` file that is incorrect. The `.jl.XXX.cov` files are also incorrect.

Look at one of the Julia 1.0 jobs that does have `.jl.XXX.cov` files. Look at the `parsers.jl.XXX.cov`, and specifically at the same place we've been looking, i.e. the `reinit!` function on line 121. That coverage information is incorrect.

**Comment by DilumAluthge** [comment]
But how would coverage generation be broken on Julia 1.0? We haven't even made a new release of Julia 1.0.x recently.

**Pull request closed without merging**
